//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resfile.rc
//
#define IDS_APP_TITLE                   1
#define IDS_MONITOR_TITLE               2
#define IDM_WINDOWCHILD                 3
#define IDI_ICON_BIG                    102
#define IDI_ICON_SMALL                  103
#define IDD_ABOUT                       104
#define IDC_MAIN_MDI                    105
#define IDI_BREAK                       106
#define IDD_NEWDISK                     107
#define IDD_KEYBOARD                    108
#define IDD_KEYPAGE2                    109
#define IDD_KEYPAGE4                    110
#define IDD_JOYSTICK                    111
#define IDD_KEYPAGE1                    112
#define IDD_KEYPAGE3                    113
#define IDR_SIDDRIVER                   114
#define IDR_FONT64                      115
#define IDD_BROWSEPRG                   116
#define IDB_LEDREDON                    117
#define IDB_LEDBLUEOFF                  118
#define IDB_LEDBLUEON                   119
#define IDB_LEDGREENOFF                 120
#define IDB_LEDGREENON                  121
#define IDB_LEDREDOFF                   122
#define IDD_SETTINGTAB                  123
#define IDD_SETTING2                    124
#define IDD_SETTINGTABGENERAL           125
#define IDD_SETTINGTABVIDEO             126
#define IDD_SETTINGTABAUDIO             127
#define IDD_SETTINGTABDISK              128
#define IDD_SAVED64                     148
#define IDB_REBARBKGND1                 149
#define IDB_DEBUGGERSTEPINMASK          150
#define IDB_DEBUGGERSTEPIN              151
#define IDB_DEBUGGERSTEPOUTMASK         152
#define IDB_DEBUGGERSTEPOUT             153
#define IDB_DEBUGGERSTEPOVERMASK        154
#define IDB_DEBUGGERSTEPOVER            155
#define IDD_SETTINGTABCHIP              160
#define IDB_BREAK                       161
#define IDB_DEBUGGERSTEPONECLOCK        163
#define IDB_DEBUGGERSTEPONECLOCKMASK    164
#define IDB_DEBUGGERTRACE               165
#define IDB_DEBUGGERTRACEMASK           166
#define IDB_DEBUGGERSTOP                167
#define IDB_DEBUGGERSTOPMASK            168
#define IDB_DEBUGGERTRACEFRAME          170
#define IDB_DEBUGGERTRACEFRAMEMASK      171
#define IDB_DEBUGGERTRACEINT            173
#define IDB_BITMAP1                     174
#define IDB_DEBUGGERTRACEINTMASK        174
#define IDB_BITMAP2                     178
#define IDB_DEBUGGERTRACEINT_64         178
#define IDB_BITMAP3                     179
#define IDB_BREAKDISABLE                179
#define IDC_MAIN_WINEMULATION           700
#define IDC_MAIN_WINSTATUSBAR           701
#define IDC_VERSION                     1000
#define IDC_INFO1                       1001
#define IDC_INFO2                       1002
#define IDC_INFO3                       1003
#define IDC_1541_EMULATION              1004
#define IDC_SID_EMULATION               1005
#define IDC_SHOWSPEED                   1006
#define IDC_LIMITSPEED                  1007
#define IDC_DISKNAME                    1008
#define IDC_STATIC1                     1009
#define IDC_STATIC2                     1010
#define IDC_BYTEID1                     1011
#define IDC_BYTEID2                     1012
#define IDC_VBLSYNC                     1013
#define IDC_LINESYNC                    1014
#define IDC_SKIPFRAMES                  1015
#define IDC_TXT_ARROWLEFT               1016
#define IDC_TXT_STOP                    1017
#define IDC_TXT_COMMODORE               1018
#define IDC_TXT_DEL                     1019
#define IDC_TXT_HOME                    1020
#define IDC_TXT_PLUS                    1021
#define IDC_TXT_MINUS                   1022
#define IDC_TXT_EQUAL                   1023
#define IDC_TXT_ASTERISK                1024
#define IDC_TXT_SLASH                   1025
#define IDC_TXT_POUND                   1026
#define IDC_TXT_COLON                   1027
#define IDC_TXT_AT                      1028
#define IDC_TXT_SEMICOLON               1029
#define IDC_TXT_ARROWUP                 1030
#define IDC_TXT_RESTORE                 1031
#define IDC_KEYBOARDTAB                 1032
#define IDC_CBO_JOY1DEVICE              1033
#define IDC_CBO_JOY2DEVICE              1034
#define IDC_CBO_JOY1V                   1035
#define IDC_CBO_JOY1VREV                1036
#define IDC_CBO_JOY1ENABLE              1037
#define IDC_CBO_JOY1H                   1038
#define IDC_CBO_JOY1HREV                1039
#define IDC_CBO_JOY2V                   1040
#define IDC_CBO_JOY2VREV                1041
#define IDC_CBO_JOY2ENABLE              1042
#define IDC_CBO_JOY2H                   1043
#define IDC_CBO_JOY2HREV                1044
#define IDC_TXT_CURSORDOWN              1045
#define IDC_TXT_CURSORRIGHT             1046
#define IDC_TXT_LEFTSHIFT               1047
#define IDC_TXT_RIGHTSHIFT              1048
#define IDC_TXT_CONTROL                 1049
#define IDC_TXT_A                       1050
#define IDC_TXT_L                       1051
#define IDC_TXT_W                       1052
#define IDC_TXT_D                       1053
#define IDC_TXT_JOY1FIRE                1054
#define IDC_TXT_E                       1055
#define IDC_TXT_JOY1UP                  1056
#define IDC_TXT_F                       1057
#define IDC_TXT_JOY1DOWN                1058
#define IDC_TXT_G                       1059
#define IDC_TXT_JOY1LEFT                1060
#define IDC_TXT_H                       1061
#define IDC_TXT_JOY1RIGHT               1062
#define IDC_TXT_I                       1063
#define IDC_TXT_JOY2FIRE                1064
#define IDC_TXT_J                       1065
#define IDC_TXT_JOY2UP                  1066
#define IDC_TXT_K                       1067
#define IDC_TXT_JOY2DOWN                1068
#define IDC_TXT_1                       1069
#define IDC_TXT_C                       1070
#define IDC_TXT_JOY2LEFT                1071
#define IDC_TXT_F1                      1072
#define IDC_TXT_O                       1073
#define IDC_TXT_JOY2RIGHT               1074
#define IDC_TXT_2                       1075
#define IDC_TXT_B                       1076
#define IDC_TXT_3                       1077
#define IDC_TXT_P                       1078
#define IDC_TXT_4                       1079
#define IDC_TXT_Q                       1080
#define IDC_TXT_5                       1081
#define IDC_TXT_R                       1082
#define IDC_TXT_6                       1083
#define IDC_TXT_S                       1084
#define IDC_TXT_7                       1085
#define IDC_TXT_T                       1086
#define IDC_TXT_8                       1087
#define IDC_TXT_U                       1088
#define IDC_TXT_9                       1089
#define IDC_TXT_V                       1090
#define IDC_TXT_0                       1091
#define IDC_TXT_N                       1092
#define IDC_TXT_SPACE                   1093
#define IDC_TXT_F5                      1094
#define IDC_TXT_M                       1095
#define IDC_TXT_F3                      1096
#define IDC_DOUBLER_BLIT                1097
#define IDC_TXT_F7                      1098
#define IDC_DOUBLER_CPU                 1099
#define IDC_AUDIOCLOCKSYNC              1100
#define IDC_TXT_Z                       1101
#define IDC_TXT_Y                       1102
#define IDC_HOSTCPU_FRIENDLY            1103
#define IDC_TXT_X                       1104
#define IDC_HOSTCPU_AGGRESSIVE          1105
#define IDC_SETTINGS_HOSTCPUUSAGE       1106
#define IDC_CBO_JOY1FIRE                1107
#define IDC_CBO_JOY2FIRE                1108
#define IDC_SIDDIGIBOOT                 1109
#define IDC_SID_RESAMPLE                1110
#define IDC_SID_DOWNSAMPLE              1111
#define IDC_CUSTOMPRGLIST               1112
#define IDC_LIST1                       1113
#define IDC_CHKQUICKLOAD                1114
#define IDC_SETTINGTAB                  1115
#define IDC_CBO_ADAPTER                 1116
#define IDC_CBO_MODE                    1117
#define IDC_CBO_FORMAT                  1118
#define IDC_CBO_FILTER                  1119
#define IDC_CBO_STRETCH                 1120
#define IDC_SETTING                     1289
#define IDC_SETTINGS_PIXELDOUBLER       1289
#define IDC_RAD_TRACKS40                1289
#define IDC_LBL_STRETCH                 1290
#define IDC_LBL_FILTER                  1291
#define IDC_CBO_BORDER                  1292
#define IDC_CHK_SHOWFLOPPYLED           1295
#define IDC_CBO_FPS                     1296
#define IDC_CBO_TRACKZEROSENSOR         1296
#define IDC_CHKALIGND64TRACKS           1299
#define IDC_CHK_ALIGNTRACKS             1301
#define IDC_RAD_TRACKS35                1302
#define IDC_STA_TRACKS                  1306
#define IDC_DISKONSEPARATETHREAD        1307
#define IDC_ALLOWOPPOSINGJOYSTICK       1308
#define IDC_RAD_CIA6526                 1309
#define IDC_GROUP_CIAMODE               1310
#define IDC_RAD_CIA6526A                1311
#define IDC_CHECK1                      1312
#define IDC_CHK_TIMERBBUG               1312
#define IDC_DISABLE_DWM_FULLSCREEN      1312
#define IDC_TXT_CURSORUP                1313
#define IDC_TXT_CURSORLEFT              1314
#define IDM_EXIT                        40002
#define ID_FILE_MONITOR                 40003
#define ID_HELP_ABOUT                   40004
#define ID_TAPE_INSERT                  40005
#define ID_TAPE_PLAY                    40006
#define ID_TAPE_REWIND                  40007
#define ID_TAPE_STOP                    40008
#define ID_TAPE_LOADIMAGE               40010
#define ID_SETTING_EMULATION            40011
#define ID_TOGGLEFULLSCREEN             40015
#define ID_FILE_HARDRESET               40016
#define ID_FILE_SOFTRESET               40017
#define IDS_WINCLASS_KEYPRESS           40019
#define IDS_PRESSANYKEY                 40020
#define ID_DISK_WRITEPROTECT_ON         40023
#define ID_DISK_WRITEPROTECT_OFF        40024
#define ID_DISK_INSERT_EXISTINGDISK     40028
#define ID_DISK_INSERT_NEWBLANKDISK     40029
#define ID_DISK_SAVEDISK                40030
#define ID_DISK_SAVEDISK_FDI            40030
#define ID_DISK_REMOVEDISK              40031
#define ID_SETTING_KEYBOARD             40032
#define ID_SETTING_SAVE                 40033
#define ID_SETTING_RESTOREDEFAULT       40034
#define ID_SETTING_JOYSTICK             40035
#define ID_SETTING_LOADSETTINGS_RESTOREUSER 40037
#define ID_SETTING_DOUBLESIZEDWINDOW    40038
#define ID_FILE_AUTOLOAD                40039
#define ID_SETTING_SWAPJOYSTICKS        40040
#define ID_FILE_PAUSE                   40041
#define ID_SETTING_MAXSPEED             40042
#define ID_DISK_SAVEDISK_D64            40043
#define ID_TAPE_LOADT64                 40044
#define ID_SETTING_EMULATION2           40045
#define ID_DISK_RESETDRIVE              40046
#define ID_SETTING_MUTESOUND            40047
#define ID_DEBUG_CPUC64                 40056
#define ID_DEBUG_CPUDISK                40059
#define ID_STEP_ONEINSTRUCTION          40060
#define ID_STEP_ONECLOCK                40061
#define ID_STEP_JSRSUBROUTE             40062
#define ID_STEP_TRACE                   40063
#define ID_STEP_STOP                    40070
#define ID_STEP_TRACE40071              40071
#define ID_STEP_STOP40072               40072
#define ID_MDI_STEP_TRACE               40074
#define ID_MDI_STEP_STOP                40075
#define ID_STEP_TRACEFRAME              40084
#define ID_STEP_TRACEFRAME40085         40085
#define ID_STEP_TRACEINTERRUPTTAKEN     40088

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         40089
#define _APS_NEXT_CONTROL_VALUE         1315
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
