#pragma once
#define WM_MONITOR_BREAK_CPU64 (WM_APP  + 1)
#define WM_MONITOR_BREAK_CPUDISK (WM_APP  + 2)
#define WM_MONITOR_BREAK_VICRASTER (WM_APP + 3)
#define WM_MONITOR_START_TRACE (WM_APP + 4)
