#pragma once

#define NUM_SCREEN_COLUMNS (40)
#define PIXELBUFFER_SIZE (65 *8 + 48)
#define PIXELBUFFER_MAIN_INDEX 0
#define PIXELBUFFER_BACKUP_INDEX 1
#define PIXELBUFFER_COUNT 2

#define DISPLAY_START (76)
#define GACCESS_COL1_CYCLE (16)
#define SPRITE_DISPLAY_CHECK_XPOS (0x164)